GET  http://localhost:3000/

###
GET http://localhost:3000/api/courses
###

DELETE http://localhost:3000/api/courses/1

###

PUT http://localhost:3000/api/courses/1 
Content-Type: application/json

{
    
    "name":"det här ny coruse"
}


###
POST http://localhost:3000/api/courses
Content-Type: application/json

{
    "name": "newcoruse"
}